language: go
go:
- 1.5.3
- tip


before_install:
- export REPOSITORY_ROOT=${TRAVIS_BUILD_DIR}
- go get golang.org/x/tools/cmd/vet
- go get github.com/kisielk/errcheck


script:
- go test -v -race -timeout=90s github.com/dropbox/kafka/...
- go vet github.com/dropbox/kafka/...
- errcheck github.com/dropbox/kafka/...
- go test -bench '.*' -run none github.com/dropbox/kafka/...

env:
- WITH_INTEGRATION=true GOMAXPROCS=4

sudo: false
